//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search
    {
        public int Id { get; set; }
        public System.DateTime SearchDate { get; set; }
        public int Positive { get; set; }
        public int Negative { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
